Rnn with attn
Prajakta15Patil/COVID-analysis pull request #10
Opened 2021-02-07 16:10 UTC by Prajakta15Patil

Can you please review my code covid_clustering.ipynb and covid_bert.ipynb? I have added markdowns.

2021-02-13 22:54 UTC, upomodoro requested changes
Hey Prajakta,

Thanks for putting the pull request together. There a few things you should do, but the biggest thing you can do is annotate your code some more and delete any files that are not necessary for the code to run.

1. DailyMail-Bert is just one cell?

2. What is the vis.html file?

3. Do you need code/rnn_seq2seqattn_upom.ipynb, rnn_seq2seqattn_cnn_dailymail.ipynb

4. All functions in extract_data.py need docstrings.

5. Covid-BERT.ipynb has a lot of output. It would be ideal if it was reduced.

6. covid_analysis.ipynb needs a summary and annotation

7. RNN_LSTMwithAttn.ipynb, RNN_covid.ipynb, and RNN_seq.ipynb needs annotation or to be removed.

8. You should have a README.MD to explain the project and what each of the files represent.

2021-02-13 22:54 UTC, upomodoro commented on code/extract_data.py
>  # print(len(data)) # 19458
remove comment.

2021-02-13 22:54 UTC, upomodoro commented on code/extract_data.py
>  def exportdata(data, path):
Function should have docstring

2021-02-21 15:53 UTC, Prajakta15Patil commented on code/extract_data.py
>  def exportdata(data, path):
Added docstrings in the file

2021-02-26 00:55 UTC, upomodoro requested changes
So all the notebooks look much better. However, I actually would like to see more commentary both in the notebooks and the README. To give you a sense of a more appropriate level of annotation, I've provide a link to a notebook one of my other SharpestMind Mentees made: https://github.com/drewlehe/Nashville/blob/master/Analysis.ipynb.

Let me know if you have any questions.

2021-02-28 16:19 UTC, Prajakta15Patil commented on code/extract_data.py
>  # print(len(data)) # 19458
Removed the comment

2021-03-06 22:19 UTC, upomodoro approved these changes

2021-03-06 22:20 UTC, upomodoro approved these changes

2021-03-06 23:51 UTC, merged